### ISSUE TITLE
Subscribe to locale changes

### ISSUE THREAD

**Issue by mhwk** [urish/angular2-moment#172]
**Description of the Issue and Steps to Reproduce:**
Using amTimeAgo, while changing moment locale the already rendered do not change due to the change check only occurring every once in a while. I worked around this by subscribing to the ngx/translate service and forcing a rerender. Works awesome.

Can we add a service to this library, similar to the one in ngx/translate, that all pipes can subscribe to so that if we call momentService.locale('locale'), all pipes get notified about this change and rerender itself?

Did you search for duplicate issue? [Yes / No]
Yes

Please describe the issue and steps to reproduce, preferably with a code sample / plunker:
My hacky implementation can be viewed at https://github.com/mhwk/wax/blob/master/src/wax/shared/pipes.ts

I'm willing to implement this myself and provide a pull request, however I need some help with this as I'm still learning angular. Let me know how I can help.

*Ensure your issue is isolated to angular2-moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version? 
* TypeScript version?
* `moment` version?
* Are you using `moment-timezone`? 
* Are you using the angular-cli? 
* Using Rollup/Webpack/System.js/Ionic/similar?

**Comment by lihanyu23** [comment]
I'm also looking for similar use case. 

The issue is that the actual implementation of amTimeAgo pipe doesn't take locale changes in moment.js as change so it won't update the transformed value.

The transform method is triggered when changing with moment.locale('xx') but the call to 'hasChanged' still returns false as neither the time value nor the option has changed.

I would suggest adding locale comparison in 'hasChanged' to support the use case rather than involving 3rd party lib into this.

**Comment by lukasz-kusnierz** [comment]
@urish Can you please release that fix within v1.x.x for Angular 4 users like me? Thanks!

**Comment by urish** [comment]
Yes, released as 1.9.0
