### ISSUE TITLE
Impure filters conflict with Protractor testing

### ISSUE THREAD

**Issue by tiagoroldao** [urish/angular2-moment#72]
This is due to long standing timeouts being defined within the angular zone. Protractor tests timeout whenever these pipes are present on the page.

**Comment by christiandreher** [comment]
That's interesting. Could you please take a look at [this](http://stackoverflow.com/questions/39184073/protractor-keeps-waiting-on-finished-http-requests) Stack Overflow question I opened a long time ago to confirm that this issue here could also be the cause for the problem I had? I originaly assumed that it may be due to http requests, but I think that I completely removed all moment pipes when excluding the http requests (because the timestamps come from a database) 

If the issues I describe there matches what you found out, you are active on Stack Overflow and if you want to get some reps, feel free to answer my question linking this issue or your PR.

**Comment by tiagoroldao** [comment]
I believe so. Heading to bed now, tomorrow I'll take a closer look!

**Comment by christiandreher** [comment]
Thank you very much in advance for your time :)

**Comment by tiagoroldao** [comment]
Answered 😄
